# Generated by Django 6.0.2 on 2026-03-17 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOverallPerformance',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_calls', models.IntegerField()),
                ('total_conversions', models.IntegerField()),
                ('total_target', models.IntegerField()),
                ('overall_conversion_rate', models.FloatField()),
                ('revenue_generated', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(db_index=True, max_length=200)),
                ('insurance_provider', models.CharField(max_length=200)),
                ('coverage_amount', models.FloatField()),
                ('premium', models.FloatField()),
                ('tenure', models.IntegerField()),
                ('commission_rate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('premium_amount', models.FloatField()),
                ('commission_earned', models.FloatField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurer.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_status', models.BooleanField(default=False)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurer.conversion')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('insurance_type', models.CharField(choices=[('motor', 'Motor'), ('health', 'Health'), ('life', 'Life')], max_length=10)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('sum_insured', models.FloatField()),
                ('policy_type', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('family_members', models.IntegerField(blank=True, null=True)),
                ('existing_disease', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_details', to='insurer.lead')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField()),
                ('follow_up_date', models.DateTimeField()),
                ('follow_up_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('iteration_count', models.IntegerField(default=1)),
                ('next_action', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='insurer.lead')),
            ],
        ),
        migrations.AddField(
            model_name='conversion',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurer.lead'),
        ),
        migrations.CreateModel(
            name='LifeLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=50)),
                ('nominee_name', models.CharField(max_length=50)),
                ('nominee_relation', models.CharField(max_length=50)),
                ('policy_term', models.IntegerField()),
                ('sum_assured', models.FloatField()),
                ('age', models.IntegerField()),
                ('annual_income', models.FloatField(blank=True, null=True)),
                ('smoker', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='life_details', to='insurer.lead')),
            ],
        ),
        migrations.CreateModel(
            name='MotorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rto_location', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('policy_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motor_details', to='insurer.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_target', models.IntegerField()),
                ('achieved_score', models.IntegerField()),
                ('leads_converted', models.IntegerField(default=0)),
                ('calls_made', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('target_met', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agent', 'date'), name='unique_agent_score_per_day')],
            },
        ),
    ]
