# Generated by Django 6.0.2 on 2026-03-25 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0002_dailyoverallperformance_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyoverallperformance',
            name='overall_conversion_rate',
        ),
        migrations.RemoveField(
            model_name='dailyoverallperformance',
            name='revenue_generated',
        ),
        migrations.AddField(
            model_name='dailyoverallperformance',
            name='connected_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
