# Generated by Django 6.0.2 on 2026-03-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0003_remove_dailyoverallperformance_overall_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='hot', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyoverallperformance',
            name='total_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyoverallperformance',
            name='total_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyoverallperformance',
            name='total_target',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
    ]
