# Generated by Django 6.0.2 on 2026-04-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0007_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='commission_earned',
        ),
    ]
