# Generated by Django 6.0.2 on 2026-04-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0008_remove_conversion_commission_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='commission_rate',
        ),
    ]
