# Generated by Django 6.0.2 on 2026-04-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0009_remove_insurance_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
