# Generated by Django 6.0.2 on 2026-04-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0010_alter_followup_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('not_interested', 'Not Interested')], db_index=True, default='new', max_length=20),
        ),
    ]
