# Generated by Django 6.0.4 on 2026-04-24 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0011_lead_payment_status_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('monthly_target', 'Monthly Target Achieved'), ('weekly_bonus', 'Weekly Bonus'), ('performance', 'Performance Bonus'), ('attendance', 'Login/Attendance Bonus')], max_length=20)),
                ('date_earned', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_earned'],
            },
        ),
    ]
